// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyeybovxdfpypbohdlgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55ZXlib3Z4ZGZweXBib2hkbGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzY1ODYsImV4cCI6MjA3MjU1MjU4Nn0.Q8LkywkpzI3wvgUKP44-KdA5ZfstUPpNneGJ12o3GfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});